collectd:
  build: apps/collectd
  command: /bin/bash -c "collectd -f"
  links:
    - kairosdb

kairosdb:
  build: apps/kairosdb
  command: /bin/bash -c "/opt/kairosdb/bin/kairosdb.sh run"
  ports:
   - "4242:4242"
   - "8080:8080"
  links:
   - cassandra

cassandra:
  image: jimthedev/cassandra
  hostname: cassandra
  ports:
    - "9042:9042"
    - "9160:9160"
